# Generated by Django 2.2.17 on 2021-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('Book_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
